### PR TITLE
Release 1.0.0 back to develop

### PR DESCRIPTION
**Pull request by lukeindykiewicz**

### CODE REVIEW

**Review by benjben — CHANGES_REQUESTED** [review]
Same, should be one commit and without the `close` in CHANGELOG.

**Comment by benjben** [comment]
Should be only `Prepare for release` commit

**Comment by lukeindykiewicz** [comment]
> Should be only Prepare for release commit

What do you mean by that? I have removed the `Bump to 1.0.0` commit.

**Comment by lukeindykiewicz** [comment]
If you mean any other commit in this branch, no it shouldn't. It was explained in the mirror PR to master, please check: https://github.com/snowplow/scala-weather/pull/130#issue-474907941

> That's due to change to gitflow workflow in the middle of this "release"

This both PRs are a pair. I also write in internal channel that the `develop` branch was forced pushed to be prepared according to gitflow-workflow, but not before any PR in this release.

**Comment by benjben** [comment]
- Reformat code
- Update scalafmt to newest
- Bump scala-lru-map to 0.5.0

are already on `develop`. Do not hesitate to force-push to develop so that we can start using gitflow as we should.

**Comment by lukeindykiewicz** [comment]
develop is mirroring master now, should be possible to work with gitflow workflow from now on

**Pull request closed without merging**
