### PR TITLE
Update dependencies (closes #89, #90, #91)

### LINKED ISSUE #89: Bump circe to 0.10.0

### PR DESCRIPTION
**Pull request by Nirajn2311**
Updated the following dependencies:-
- circe - `0.9.3` -> `0.10.0`
- lruMap - `0.1.0` -> `0.2.0`
- specs2 - `3.9.4` -> `4.3.4`

### CODE REVIEW

**Comment by BenFradet** [comment]
Hello, thanks a lot for the PR!

Please read our contributing guide, in particular the sections about:

- [commit hygiene](https://github.com/snowplow/scala-weather/blob/develop/CONTRIBUTING.md#commit-hygiene)
- [our CLA](https://github.com/snowplow/scala-weather/blob/develop/CONTRIBUTING.md#contributor-license-agreement)

**Comment by Nirajn2311** [comment]
I just signed the cla and commit message follows the required conditions, so I don’t get it why Travis is failing.

**Comment by BenFradet** [comment]
Hello, we require one commit per issue, from the contributing guide:

>We keep a strict 1-to-1 correspondance between commits and issues, as such our commit messages are formatted in the following fashion:
Add issues description (closes #1234)

**Comment by Nirajn2311** [comment]
Ah sorry about that, will close this and do three separate PRs

**Comment by BenFradet** [comment]
No worries!

**Pull request closed without merging**
